#%RAML 1.0 Library
types:
  account:
    type: object
    properties:
      account_name: 
        type: string
        required: true
      account_type:
        type: string
        required: true
      account_sub_type:
        type: string
        required: true
      account_create_date:
        type: date-only
        required: false
      account_detail:
        type: string
        required: false
    
 
  