#%RAML 1.0 Library
types:
  api-status:
    type: object
    properties:
      status: 
        type: string
        required: true
      version:
        type: string
        required: true
      time:
        type: string
        required: true

  sync-response:
    type: object
    properties:
      message:
        type: string
        required: true

  async-response:
    type: object
    properties:
      message:
        type: string
        required: false
      correlation-id: 
        type: string
        required: true
        pattern: "([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}"
      detail:
        type: string
        required: true
      timestamp: 
        type: datetime
        required: true
     