#%RAML 1.0 ResourceType

get?:
  displayName: <<resourcePathName|!singularize|!uppercamelcase>>
  description: Get a item of a <<resourcePathName>>.
  responses:
    200:
      body:
        <<content-type>>:
          description: A item of <<resourcePathName>>. If no <<resourcePathName|!singularize|!uppercamelcase>> was found, a empty item is returned.
          type: <<type-get-response>> 
          examples: <<examples-get-response>>
           
delete?:
  displayName: <<resourcePathName|!singularize>>
  description: Delete an <<resourcePathName|!singularize>> based on information provided.
  body: 
    <<content-type>>:
      description: <<resourcePathName|!singularize>> to be deleted.
      type: <<type-delete-request>>
      examples: <<examples-delete-request>>
  responses: 
    200:
      body: 
        <<content-type>>:
          description: Returns the <<resourcePathName|!singularize>> deleted.
          type: <<type-delete-response>>
          examples: <<examples-delete-response>>

patch?:
  displayName: <<resourcePathName|!singularize>>
  description: Update an <<resourcePathName|!singularize>> based on information provided.
  body: 
    <<content-type>>:
      description: <<resourcePathName|!singularize>> to be updated.
      type: <<type-patch-request>>
      examples: <<examples-patch-request>>
  responses: 
    200:
      body: 
        <<content-type>>:
          description: Returns the updated <<resourcePathName|!singularize>>.
          type: <<type-patch-response>>
          examples: <<examples-patch-response>>
put?:
  displayName: <<resourcePathName|!singularize>>
  description: Update an <<resourcePathName|!singularize>> based on information provided.
  body: 
    <<content-type>>:
      description:  <<resourcePathName|!singularize>> to be updated.
      type: <<type-put-request>>
      examples: <<examples-put-request>>
  responses: 
    200:
      body: 
        <<content-type>>:
          description: Returns the <<resourcePathName|!singularize>> updated.
          type: <<type-put-response>>
          examples: <<examples-put-response>>
post?:
  displayName: <<resourcePathName|!singularize>>
  description: create an <<resourcePathName|!singularize>> based on information provided.
  body: 
    <<content-type>>:
      description: <<resourcePathName|!singularize>> to be created.
      type: <<type-post-request>>
      examples: <<examples-post-request>>
  responses: 
    201:
      headers:
        Location:
          description: Location of the resource created.
          type: string
          example: /resource/123
          required: true
        ETag:
          description: An identifier for a specific version of a resource.
          type: string
          example: bfc13a84729c4290ef8b2c2730249c88ca92d82d
          required: false
      body: 
        <<content-type>>:
          description: Returns the <<resourcePathName|!singularize>> created.
          type: <<type-post-response>>
          examples: <<examples-post-response>>