#%RAML 1.0 Trait

headers: 
  client_id:
    description: Identifies the unique consumer identifier.
    required: true
    example: 56d97d592c30400e883ebe3244cb2c11
  client_secret:
    description: Represents the consumer secret.
    required: true
    example: C4ADd188F8511AF6937C51CDc88d1234